name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/test.yml'
    branches:
      - main
      - dev
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `ui`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/ui
          token: ${{ secrets.PAT }}
          path: ui
      
      - name: Checkout `clipboard`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/clipboard
          token: ${{ secrets.PAT }}
          path: clipboard
      
      - name: Checkout `transforms`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/rendering
          token: ${{ secrets.PAT }}
          path: rendering
      
      - name: Checkout `shaders`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shaders
          token: ${{ secrets.PAT }}
          path: shaders
      
      - name: Checkout `meshes`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/meshes
          token: ${{ secrets.PAT }}
          path: meshes
      
      - name: Checkout `materials`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/materials
          token: ${{ secrets.PAT }}
          path: materials
      
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `data`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/collections
          token: ${{ secrets.PAT }}
          path: collections
      
      - name: Checkout `text-rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/text-rendering
          token: ${{ secrets.PAT }}
          path: text-rendering
      
      - name: Checkout `meshes-9s`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/meshes-9s
          token: ${{ secrets.PAT }}
          path: meshes-9s
      
      - name: Checkout `default-presentation-assets`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/default-presentation-assets
          token: ${{ secrets.PAT }}
          path: default-presentation-assets
      
      - name: Checkout `cameras`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/cameras
          token: ${{ secrets.PAT }}
          path: cameras
      
      - name: Checkout `automations`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/automations
          token: ${{ secrets.PAT }}
          path: automations
      
      - name: Checkout `transform-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transform-systems
          token: ${{ secrets.PAT }}
          path: transform-systems
      
      - name: Checkout `textures`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/textures
          token: ${{ secrets.PAT }}
          path: textures
      
      - name: Checkout `fonts`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/fonts
          token: ${{ secrets.PAT }}
          path: fonts
      
      - name: Checkout `bin-packer`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/bin-packer
          token: ${{ secrets.PAT }}
          path: bin-packer
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:  10.0.x
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Debug --logger "trx"
            
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          working-directory: ${{ github.event.repository.name }}
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false